platformName: Android
platformVersion: '12'
deviceName: Galaxy S10e
noReset: false
resetKeyboard: true
appPackage: in.dradhanus.liveher
appActivity: in.dradhanus.liveher.SplashActivity
unicodeKeyboard: 'true'
udid: R38M20C7D8P
ip: 127.0.0.1
port: 4723



